#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Jan 16 09:15:59 KST 2026
maven-metadata-id_-1925759380_0.xml.lastUpdated=1768522559574
